version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=Th3gr3at
  
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    image: bank_x_webservice_uat_v1 
    ports:
      - '909:3000'
    depends_on:
      - mysql
    # environment:
    #   - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/my_database?useSSL=false&serverTimezone=UTC
    #   - SPRING_DATASOURCE_USERNAME=db_user
    #   - SPRING_DATASOURCE_PASSWORD=db_password
volumes:
  mysql-data:
