version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=Th3gr3at
  
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    image: bank_x_webservice_uat_v1 
    ports:
      - '909:3000'
    depends_on:
      - mysql

volumes:
  mysql-data:
