version: '3'
services:
  db:
    image: postgres:latest
    container_name: bank_x_postgress
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=8@nk_x_PA55CoD3
      - POSTGRES_DB=db
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
